### ISSUE TITLE
Gui doesn't reappear after reload

### ISSUE THREAD

**Issue by tim-vu** [kapraran/vu-debug-gui#1]
As the title says, the gui doesn't reappear after reloading mods. Rejoining the game fixes this.
I thought the issue might be caused due to the order in which the mods load, however after adding a dependency to vu-debug-gui the gui still doesn't reappear

**Comment by kapraran** [comment]
Maybe you are registering some controls after they've been requested by the client. 
I'll look into it but for now try calling `DebugGUI:Show()` after registering the controls.

**Comment by kapraran** [comment]
I updated the code, [download it from here](https://community.veniceunleashed.net/t/debuggui-create-gui-debug-controls-with-ease/2661) if you want the precompiled ui.vuic. Dont forget to copy the updated `DebugGUI.lua` file into you mod. Please let me know if this fixed your issue.
