### ISSUE TITLE
UI - WebUI.Call throttle - Silent crash can occur without throttle

### ISSUE THREAD

**Issue by kaloczikvn** [kapraran/vu-debug-gui#5]
https://github.com/kapraran/vu-debug-gui/blob/b90dc6a21566a392c633252ec29499c1eccf7243/ui/src/app/index.js#L33

Commented out this function and worked fine, but as soon as I uncommented and played around with the sliders I silent crashed (from time to time, hard to reproduce).

**Comment by kapraran** [comment]
fixed in https://github.com/kapraran/vu-debug-gui/commit/0eefd625d698c66d9aba9c4e201c3ceeeafdbf6d
